import Head from 'next/head'
import Image from 'next/image'


import { makeStyles, useTheme } from '@mui/styles'
import { Container, Box } from '@mui/material'


// const useStyles = makeStyles((theme) => ({
//   root: {
//     backgroundColor: theme.palette.common.white
//   }

// }));

export default function HomePage() {
  //const theme = useTheme();
  //const classes = useStyles(theme);

  return (
      <>
          <Container
             // className={classes.root}
              disableGutters={true}
              maxWidth={false}
          >
              <Box>
                  <h1>Home Page</h1>
                  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat molestiae alias minus maiores atque quaerat tempora deserunt nemo! Dicta totam eveniet delectus minus! Ex itaque illum laboriosam quisquam autem corrupti?
                  Porro ipsa beatae pariatur minima illo libero sit, aliquid in id quasi, voluptatem sapiente rerum necessitatibus quos consequatur exercitationem reprehenderit, dolorum deleniti praesentium dicta? Deserunt maiores adipisci maxime est odio.
                  Inventore optio doloribus quis, esse, natus ex aperiam amet molestias voluptate assumenda voluptas totam quibusdam quam neque illum saepe cupiditate sed iusto non minus vel iste atque! Temporibus, fuga in?
                  Facilis sapiente vero, vitae dolorem obcaecati accusantium ad minima cumque et doloremque, quos nihil reiciendis reprehenderit officiis harum aut ab, sint fugit ex ea. Similique aliquam ea repellendus a corporis?
                  Error reiciendis at ex voluptate quos quia hic, distinctio et, explicabo, vitae in facere optio eligendi officiis ea repellendus vel eveniet laudantium? Voluptatem deserunt doloribus, quia obcaecati incidunt fugit eveniet!
                  Sequi dolorem fugiat dignissimos nulla odit dolore adipisci debitis officia ex maxime eum explicabo nobis sint assumenda velit et beatae perspiciatis suscipit, nam inventore minima tempora. Officiis nostrum tempore consequatur!
                  Rerum aliquid iste atque dignissimos! Autem rem eius consequuntur nulla corrupti! Nesciunt ea, dicta fugit voluptatibus nobis laudantium rem itaque id vitae eum pariatur iste sunt provident perferendis? Itaque, dignissimos.
                  Temporibus, debitis? Ut reprehenderit corporis laudantium fugiat, pariatur quis, cum error maiores minus quod voluptatem sapiente eum doloribus soluta enim quas, excepturi minima voluptatum facere aperiam eos. Voluptatibus, earum explicabo.
                  Est inventore, quisquam dignissimos non ullam placeat sequi consequuntur, quos perferendis nisi incidunt quasi qui unde saepe libero a quibusdam? Repellendus cum neque eaque nobis veniam explicabo reprehenderit enim aliquid!
                  Illum numquam, non explicabo aliquid dicta repellat! Vero quae quasi commodi quidem eveniet quam quis asperiores ratione, ab molestiae repellendus in assumenda, odio debitis beatae? Voluptate nulla eum in harum!
                  Quae eos possimus tenetur, modi totam dolor fugiat laboriosam optio culpa perspiciatis porro unde eaque amet itaque, inventore, corrupti sed vitae accusamus magni dolores exercitationem! Architecto unde error inventore voluptate.
                  Et nesciunt amet cupiditate optio quia magni perferendis, est enim nobis rerum voluptatem! Placeat quod beatae in hic iusto fugiat quis obcaecati commodi vitae aperiam, at laborum, quos quisquam minima?
                  At architecto cum accusantium. Necessitatibus voluptates molestiae atque dolor provident placeat quaerat, repudiandae suscipit sed maiores itaque sit nemo dignissimos facilis alias ipsam excepturi eligendi ex numquam et? Est, quia.
                  Ab rem iste quod explicabo cumque temporibus, autem reiciendis accusantium praesentium nihil cupiditate eveniet quos fuga deleniti molestias velit molestiae earum, animi assumenda rerum, recusandae corrupti tempora. Sed, fuga quos.
                  Distinctio inventore necessitatibus quia incidunt fugiat ducimus repellat, facilis iste ipsa quod error rem, cupiditate atque! Earum perferendis pariatur, sed, explicabo obcaecati modi velit excepturi amet ipsam aspernatur eos esse.</p>

              </Box>
          </Container> 

      </>
    
  )

}

// export default function Home() {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to <a href="https://nextjs.org">Next.js!</a>
//         </h1>

//         <p className={styles.description}>
//           Get started by editing{' '}
//           <code className={styles.code}>pages/index.js</code>
//         </p>

//         <div className={styles.grid}>
//           <a href="https://nextjs.org/docs" className={styles.card}>
//             <h2>Documentation &rarr;</h2>
//             <p>Find in-depth information about Next.js features and API.</p>
//           </a>

//           <a href="https://nextjs.org/learn" className={styles.card}>
//             <h2>Learn &rarr;</h2>
//             <p>Learn about Next.js in an interactive course with quizzes!</p>
//           </a>

//           <a
//             href="https://github.com/vercel/next.js/tree/canary/examples"
//             className={styles.card}
//           >
//             <h2>Examples &rarr;</h2>
//             <p>Discover and deploy boilerplate example Next.js projects.</p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//           >
//             <h2>Deploy &rarr;</h2>
//             <p>
//               Instantly deploy your Next.js site to a public URL with Vercel.
//             </p>
//           </a>
//         </div>
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{' '}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }
